apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: homework
        image: hongbiao/homework
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8077
          name: homework
---
apiVersion: v1
kind: Service
metadata:
  name: homework
spec:
  type: LoadBalancer
  ports:
  - port: 8077
  selector:
    app: homework

